# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mirror Fashion
description: Loja de Roupa e Acessórios
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.mirrorfashion.com.br/" # the base hostname & protocol for your site
description: "_site"
exclude: ["bower_components","node_modules", "package.json", "bower.json", "gulpfile.js", "projeto.json", "README.md"]

# Build settings
markdown: kramdown
